- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop thethinh
   - name: remove container
     shell: docker container rm thethinh
   - name: remove docker image
     shell: docker image rmi lavi1205/docker_webapp
   - name: create new container
     shell: docker container run -itd --name thethinh -p 9000:80 lavi1205/docker_webapp